name: Buildscript

on:
  push:
    paths:
      - '.github/workflows/build-logic.yml'
      - 'build-logic/**'
  pull_request:
    paths:
      - '.github/workflows/build-logic.yml'
      - 'build-logic/**'
env:
  TERM: dumb

jobs:
  build-logic:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      - name: Build build-logic
        working-directory: build-logic
        run: ./gradlew build